import os

# API_SECRET = os.environ["API_SECRET"]
# TELEGRAM_BOT_API_KEY = os.environ["TELEGRAM_BOT_API_KEY"]
# TELEGRAM_CHAT_ID = os.environ["TELEGRAM_CHAT_ID"].split(",")
TELEGRAM_API_URL = "https://api.telegram.org/bot"
# SOLARWINDS_LOG_SERVER_IP = os.environ["SOLARWINDS_LOG_SERVER_IP"]
# SOLARWINDS_LOG_SERVER_PORT = int(os.environ["SOLARWINDS_LOG_SERVER_PORT"])
TELEGRAM_CRYPTO_BOT_API_KEY = "5627580608:AAHaE18ErU1tl9wT_pZLLLUZAKC1SqnBL_I"
TELEGRAM_FOREX_BOT_API_KEY = "6097582502:AAH90TML0hcnpwNUM6284ZqSpuTWbWL3fCM"
TELEGRAM_CHAT_ID = "676498090".split(",")
API_SECRET = "9A6588FC489BE1C95FAFCEB3426EC"
SOLARWINDS_LOG_SERVER_IP = "logs6.papertrailapp.com"
SOLARWINDS_LOG_SERVER_PORT = 48212
